# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Erhan67/Desktop/MusPRJ/MusPRJ/src/home_3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/artialti.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    \n"
"    \n"
"    background-color: rgb(170, 170, 127);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_ses_gonder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ses_gonder.sizePolicy().hasHeightForWidth())
        self.pushButton_ses_gonder.setSizePolicy(sizePolicy)
        self.pushButton_ses_gonder.setMinimumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ses_gonder.setFont(font)
        self.pushButton_ses_gonder.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(85, 170, 255);")
        self.pushButton_ses_gonder.setCheckable(False)
        self.pushButton_ses_gonder.setObjectName("pushButton_ses_gonder")
        self.horizontalLayout_4.addWidget(self.pushButton_ses_gonder)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pushButton_usbden_yukle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_usbden_yukle.sizePolicy().hasHeightForWidth())
        self.pushButton_usbden_yukle.setSizePolicy(sizePolicy)
        self.pushButton_usbden_yukle.setMinimumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_usbden_yukle.setFont(font)
        self.pushButton_usbden_yukle.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius:15px;")
        self.pushButton_usbden_yukle.setObjectName("pushButton_usbden_yukle")
        self.horizontalLayout_5.addWidget(self.pushButton_usbden_yukle)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.gridLayout_11.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(0, -1, -1, 9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 0, 0, 1, 1)
        self.pushButton_hoparlor_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_hoparlor_1.sizePolicy().hasHeightForWidth())
        self.pushButton_hoparlor_1.setSizePolicy(sizePolicy)
        self.pushButton_hoparlor_1.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_1.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_1.setStyleSheet("border-image: url(:/icons/icons/koyu_kirmizi.jpg);\n"
"background-color: rgba(255, 255, 255,0);")
        self.pushButton_hoparlor_1.setText("")
        self.pushButton_hoparlor_1.setObjectName("pushButton_hoparlor_1")
        self.gridLayout_9.addWidget(self.pushButton_hoparlor_1, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 0, 2, 1, 1)
        self.pushButton_hoparlor_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hoparlor_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_2.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_2.setStyleSheet("border-image: url(:/icons/icons/koyu_kirmizi.jpg);")
        self.pushButton_hoparlor_2.setText("")
        self.pushButton_hoparlor_2.setObjectName("pushButton_hoparlor_2")
        self.gridLayout_9.addWidget(self.pushButton_hoparlor_2, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 4, 1, 1)
        self.pushButton_hoparlor_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hoparlor_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_3.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_3.setStyleSheet("border-image: url(:/icons/icons/koyu_kirmizi.jpg);")
        self.pushButton_hoparlor_3.setText("")
        self.pushButton_hoparlor_3.setObjectName("pushButton_hoparlor_3")
        self.gridLayout_9.addWidget(self.pushButton_hoparlor_3, 0, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 6, 1, 1)
        self.pushButton_hoparlor_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hoparlor_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_4.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_4.setStyleSheet("border-image: url(:/icons/icons/koyu_kirmizi.jpg);")
        self.pushButton_hoparlor_4.setText("")
        self.pushButton_hoparlor_4.setObjectName("pushButton_hoparlor_4")
        self.gridLayout_9.addWidget(self.pushButton_hoparlor_4, 0, 7, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 0, 8, 1, 1)
        self.pushButton_hoparlor_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hoparlor_5.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_5.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_5.setStyleSheet("border-image: url(:/icons/icons/koyu_kirmizi.jpg);")
        self.pushButton_hoparlor_5.setText("")
        self.pushButton_hoparlor_5.setObjectName("pushButton_hoparlor_5")
        self.gridLayout_9.addWidget(self.pushButton_hoparlor_5, 0, 9, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 0, 10, 1, 1)
        self.pushButton_hoparlor_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hoparlor_6.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_6.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_6.setStyleSheet("border-image: url(:/icons/icons/koyu_kirmizi.jpg);")
        self.pushButton_hoparlor_6.setText("")
        self.pushButton_hoparlor_6.setObjectName("pushButton_hoparlor_6")
        self.gridLayout_9.addWidget(self.pushButton_hoparlor_6, 0, 11, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 0, 12, 1, 1)
        self.pushButton_hoparlor_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hoparlor_7.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_7.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_7.setStyleSheet("border-image: url(:/icons/icons/koyu_kirmizi.jpg);")
        self.pushButton_hoparlor_7.setText("")
        self.pushButton_hoparlor_7.setObjectName("pushButton_hoparlor_7")
        self.gridLayout_9.addWidget(self.pushButton_hoparlor_7, 0, 13, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 0, 14, 1, 1)
        self.pushButton_hoparlor_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hoparlor_8.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_8.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_hoparlor_8.setStyleSheet("border-image: url(:/icons/icons/koyu_kirmizi.jpg);")
        self.pushButton_hoparlor_8.setText("")
        self.pushButton_hoparlor_8.setObjectName("pushButton_hoparlor_8")
        self.gridLayout_9.addWidget(self.pushButton_hoparlor_8, 0, 15, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem12, 0, 16, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setContentsMargins(-1, -1, -1, 61)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem13 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem13, 0, 0, 1, 1)
        self.label_hoparlor_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hoparlor_1.sizePolicy().hasHeightForWidth())
        self.label_hoparlor_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hoparlor_1.setFont(font)
        self.label_hoparlor_1.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_hoparlor_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hoparlor_1.setObjectName("label_hoparlor_1")
        self.gridLayout_13.addWidget(self.label_hoparlor_1, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem14, 0, 2, 1, 1)
        self.label_hoparlor_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hoparlor_2.sizePolicy().hasHeightForWidth())
        self.label_hoparlor_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hoparlor_2.setFont(font)
        self.label_hoparlor_2.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_hoparlor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hoparlor_2.setObjectName("label_hoparlor_2")
        self.gridLayout_13.addWidget(self.label_hoparlor_2, 0, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem15, 0, 4, 1, 1)
        self.label_hoparlor_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hoparlor_3.sizePolicy().hasHeightForWidth())
        self.label_hoparlor_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hoparlor_3.setFont(font)
        self.label_hoparlor_3.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_hoparlor_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hoparlor_3.setObjectName("label_hoparlor_3")
        self.gridLayout_13.addWidget(self.label_hoparlor_3, 0, 5, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem16, 0, 6, 1, 1)
        self.label_hoparlor_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hoparlor_4.sizePolicy().hasHeightForWidth())
        self.label_hoparlor_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hoparlor_4.setFont(font)
        self.label_hoparlor_4.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_hoparlor_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hoparlor_4.setObjectName("label_hoparlor_4")
        self.gridLayout_13.addWidget(self.label_hoparlor_4, 0, 7, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem17, 0, 8, 1, 1)
        self.label_hoparlor_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hoparlor_5.sizePolicy().hasHeightForWidth())
        self.label_hoparlor_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hoparlor_5.setFont(font)
        self.label_hoparlor_5.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_hoparlor_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hoparlor_5.setObjectName("label_hoparlor_5")
        self.gridLayout_13.addWidget(self.label_hoparlor_5, 0, 9, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem18, 0, 10, 1, 1)
        self.label_hoparlor_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hoparlor_6.sizePolicy().hasHeightForWidth())
        self.label_hoparlor_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hoparlor_6.setFont(font)
        self.label_hoparlor_6.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_hoparlor_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hoparlor_6.setObjectName("label_hoparlor_6")
        self.gridLayout_13.addWidget(self.label_hoparlor_6, 0, 11, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem19, 0, 12, 1, 1)
        self.label_hoparlor_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hoparlor_7.sizePolicy().hasHeightForWidth())
        self.label_hoparlor_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hoparlor_7.setFont(font)
        self.label_hoparlor_7.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_hoparlor_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hoparlor_7.setObjectName("label_hoparlor_7")
        self.gridLayout_13.addWidget(self.label_hoparlor_7, 0, 13, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem20, 0, 14, 1, 1)
        self.label_hoparlor_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hoparlor_8.sizePolicy().hasHeightForWidth())
        self.label_hoparlor_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hoparlor_8.setFont(font)
        self.label_hoparlor_8.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_hoparlor_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hoparlor_8.setObjectName("label_hoparlor_8")
        self.gridLayout_13.addWidget(self.label_hoparlor_8, 0, 15, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem21, 0, 16, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem22)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 16, -1, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem23)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem24)
        self.radioButton_anons1 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_anons1.sizePolicy().hasHeightForWidth())
        self.radioButton_anons1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_anons1.setFont(font)
        self.radioButton_anons1.setCheckable(True)
        self.radioButton_anons1.setChecked(False)
        self.radioButton_anons1.setObjectName("radioButton_anons1")
        self.verticalLayout.addWidget(self.radioButton_anons1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem25)
        self.radioButton_anons2 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_anons2.sizePolicy().hasHeightForWidth())
        self.radioButton_anons2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_anons2.setFont(font)
        self.radioButton_anons2.setObjectName("radioButton_anons2")
        self.verticalLayout.addWidget(self.radioButton_anons2)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem26)
        self.radioButton_anons3 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_anons3.sizePolicy().hasHeightForWidth())
        self.radioButton_anons3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_anons3.setFont(font)
        self.radioButton_anons3.setObjectName("radioButton_anons3")
        self.verticalLayout.addWidget(self.radioButton_anons3)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem27)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.acilButton = QtWidgets.QPushButton(self.centralwidget)
        self.acilButton.setMinimumSize(QtCore.QSize(50, 50))
        self.acilButton.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.acilButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/acil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acilButton.setIcon(icon1)
        self.acilButton.setIconSize(QtCore.QSize(50, 50))
        self.acilButton.setObjectName("acilButton")
        self.horizontalLayout_8.addWidget(self.acilButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setMinimumSize(QtCore.QSize(45, 45))
        self.stopButton.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/stop.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QtCore.QSize(45, 45))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_8.addWidget(self.stopButton)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../example/images/speaker-volume.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_8.addWidget(self.volumeSlider)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem30)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout_11.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("color: rgb(35, 6, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ANASAYFA"))
        self.pushButton_ses_gonder.setText(_translate("MainWindow", "Sesi Gönder"))
        self.pushButton_usbden_yukle.setText(_translate("MainWindow", "USB\'den Yükle"))
        self.label_hoparlor_1.setText(_translate("MainWindow", "Hoparlör 1"))
        self.label_hoparlor_2.setText(_translate("MainWindow", "Hoparlör 2"))
        self.label_hoparlor_3.setText(_translate("MainWindow", "Hoparlör 3"))
        self.label_hoparlor_4.setText(_translate("MainWindow", "Hoparlör 4"))
        self.label_hoparlor_5.setText(_translate("MainWindow", "Hoparlör 5"))
        self.label_hoparlor_6.setText(_translate("MainWindow", "Hoparlör 6"))
        self.label_hoparlor_7.setText(_translate("MainWindow", "Hoparlör 7"))
        self.label_hoparlor_8.setText(_translate("MainWindow", "Hoparlör 8"))
        self.radioButton_anons1.setText(_translate("MainWindow", "Anons_1"))
        self.radioButton_anons2.setText(_translate("MainWindow", "Anons_2"))
        self.radioButton_anons3.setText(_translate("MainWindow", "Anons_3"))

import icons_rc
